CREATE DATABASE  IF NOT EXISTS RD 
USE RD;


CREATE TABLE people (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(45) NOT NULL,
  city varchar(45) DEFAULT NULL,
  contactNo varchar(10) DEFAULT NULL,
  photoUrl text,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


CREATE TABLE relations (
  p1 int NOT NULL,
  p2 int NOT NULL,
  name varchar(45) NOT NULL,
  PRIMARY KEY (p1,p2),
  KEY p2_FK_idx (p2),
  CONSTRAINT p1_Fk FOREIGN KEY (p1) REFERENCES people (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT p2_FK FOREIGN KEY (p2) REFERENCES people (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
